TUM-live:
  "EidTI": "2024/S/EidTI:COMB"
  "GRNVS": "2024/S/grnvs:COMB"
  "DWT": "2024/S/DW:COMB"
Panopto:
  "Biological Imaging": "b87a3aa9-6f30-4fe3-9804-adcc00c7b486"

asdf

Keep-Original-File: true
Jumpcut: true

Output-Folder: "/app/output"

Maximum-Parallel-Downloads: 3
